# Generated by Django 2.1.7 on 2019-03-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(default='2019-03-24 01:35:51.267134'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='module',
            name='describe',
            field=models.TextField(default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=1, verbose_name='状态'),
        ),
    ]
